export const dynamic = "force-dynamic";

function createPresentationPdf() {
  const objects: string[] = [];

  objects[1] = `<< /Type /Catalog /Pages 2 0 R >>`;
  objects[2] = `<< /Type /Pages /Kids [3 0 R] /Count 1 >>`;
  objects[3] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`;
  objects[4] = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`;

  const content = `BT /F1 28 Tf 72 700 Td (Hands on Peel) Tj ET\nBT /F1 16 Tf 72 660 Td (A digital heritage platform for Crafts on Peel) Tj ET\nBT /F1 12 Tf 72 620 Td (This PDF is generated by the app so the download button works reliably.) Tj ET\n`;
  objects[5] = `<< /Length ${content.length} >>\nstream\n${content}endstream`;

  let pdf = `%PDF-1.4\n`;
  const offsets: number[] = [0];

  for (let i = 1; i <= 5; i += 1) {
    offsets[i] = pdf.length;
    pdf += `${i} 0 obj\n${objects[i]}\nendobj\n`;
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 6\n`;
  pdf += `0000000000 65535 f \n`;
  for (let i = 1; i <= 5; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "latin1");
}

export function GET() {
  const pdf = createPresentationPdf();

  return new Response(pdf, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition":
        'attachment; filename="Hands_on_Peel_Presentation.pdf"',
      "Content-Length": String(pdf.length),
    },
  });
}
